typed/declaration/examples.ipldsch, typed/declaration/examples.ipldsch.json, typed/declaration/schema-schema.ipldsch, typed/declaration/schema-schema.ipldsch.json
The title should say it all -- herein we have a self-describing schema :)
There's a lot of commits in between the start and this result, almost all with long commit messages that are worth reading if you want to follow the intermediate decision making in detail.  I won't reproduce all of them here -- the commit log exists, in its wonderful decentralized form -- just want to draw the reader's attention to the fact there is in fact text there, and it's meant for consumption.
Short highlights:
- This is a schema!
- [There's already some docs in another file over at `doc/schema.md`](https://github.com/ipld/go-ipld-prime/blob/schema-schema/doc/schema.md).
- It's designed around "structural typing" -- being aimed at serial data, that is our defacto reality.
- (But take note: you can get …
=> Schema schema!

repose/multicodecBuiltinCbor.go, repose/repose.go, traversal/fns.go, traversal/selector/selector.go
This is a proposal for some changes that are neccessary in order to write the IPLD bridge I am using in go-graphsync -- the intent is not to merge immediately. It is more of an FYI for discussion
- Fix some compile problems (import cycles, etc) that prevent go-ipld-prime being used by other packages
- Add a few more proposed changes that would be needed for the neccesary go-ipld-prime functions to be written
- Uncomment a LinkLoader being part of TraversalConfig
- Add a proposed `ReifySelector` method that given an IPLD node that is a selector spec, returns a Selector interface
What I am looking for is anything that feels undoable -- if you end up fixing the import cycle in a different way, no problem. If a proposed function signature feels wildly off, that's important to understand.
=> WIP: Changes needed to make IPLD usable by go-graphsync

linking/cid/multicodecRegistry.go
I'm getting a panic on load for using go-ipld-prime in RegisterMulticodecDecoder and I assume it's cause the multicode tables aren't actually allocated.
=> fix(cidlink): init multicodec registry

path.go, traversal/fns.go, traversal/selector/selectAll.go, traversal/selector/selectFields.go, traversal/selector/selectTrue.go, traversal/selector/selectUnion.go, traversal/selector/selector.go, traversal/traverse.go, traversal/traverse_test.go
This is a first pass at some selector implementation...!  (At long last.)
Corresponding updates to the descriptions of selectors in the ipld/specs repo will be coming soon; the schema has changed somewhat significantly.  (I've got drafts of this change as well, but need to finish updating all the examples.)
Comments in the body should be fairly sufficient to grok if you already grok schemas and you've seen some of the more recent stuff -- e.g. the `ParseSelector` function is basically a manually-rolled implementation of unpacking a "keyed union" representation.
So far there's just outlines of implementations of a few of the basic ones.  The Selector interface as a whole sprouted a few more methods better distinguish from exploration vs matching, and to provide a way for selectors to hint …
=> Selector implementation!

errors.go, fluent/fluentRecover_test.go, impl/free/freeNode.go, impl/typed/typedNode.go, kind.go, schema/gen/go/_test/wow_test.go, schema/gen/go/gen.go, schema/gen/go/genKindString.go, schema/gen/go/genKindStringReprString.go, schema/gen/go/gen_test.go, schema/gen/go/templateUtil.go
Some forward progress on codegen.
This is a continuing WIP and still only demonstrates some very basic features for very basic types -- but, we do have some working demonstrations here.  And particularly excitingly, a short test that shows unmarshalling working on a generated type!
I've attempted to add some more types to the generation PoC on my local working copy, but have learned that already there's going to be more refinement needed on this approach to minimize the rate of growth in redundant code.  So this is probably going to be a good place to checkpoint before embarking on that.
Also, a new nicely-typed error was added to the main IPLD package, and the other existing node implementations refactored to use it.  So I want to merge this sooner than later, as it has effects outside …
=> Schema and codegen fun

encoding/dagcbor/marshal.go, encoding/dagcbor/unmarshal.go
go-ipld-cbor encodes a 0 byte ahead of cid bytes for multibase support - to maintain compatibility
of nodes encoded to CBOR, add this to encoder of go-ipld-prime.
=> fix(encoding): match go-ipld-cbor cid encoding

node.go, path.go, path_test.go, traversal/focus.go, traversal/selector/exploreAll.go, traversal/selector/exploreFields.go, traversal/selector/exploreFields_test.go, traversal/selector/exploreIndex.go, traversal/selector/exploreIndex_test.go, traversal/selector/exploreRange.go, traversal/selector/exploreRange_test.go, traversal/selector/exploreRecursive.go, traversal/selector/exploreRecursiveEdge.go, traversal/selector/exploreRecursive_test.go, traversal/selector/exploreUnion.go, traversal/selector/exploreUnion_test.go, traversal/selector/matcher.go, traversal/selector/selector.go, traversal/walk.go
ipld.Path is now a slice of ipld.PathSegment instead of strings.
This should be an improvment in sanity: there are now several fewer places importing "strconv", and that's just always a good thing.
We will also be free in the future to add PathSegment-based accessor methods to ipld.Node, as has already been commented as a desire; and, to use PathSegment in building better typed errors (which is the specific thing that provokes this diff today and now).
The implementation of PathSegment is now also based on a struct-style union rather than an interface style union.  There are comments about this in the diff.  I do not wish to comment on how much time I've spent looking at golang assembler and runtime internals while trying to find a path to a more perfect compromise between ergonomics and …
=> Move selector.PathSegment up to ipld.PathSegment.

encoding/dagcbor/unmarshal.go, encoding/dagjson/unmarshal.go, encoding/unmarshal.go, impl/free/freeNodeBuilder.go, impl/typed/wrapStruct.go, nodeBuilder.go, schema/gen/go/_test/wow_test.go, schema/gen/go/gen.go, schema/gen/go/genKindStructBuilder.go, schema/gen/go/genKindStructReprMap.go
Child-builder recursion; and typed unmarshal, working over codegen'd native structs.  This is pretty cool and a sizable milestone that confirms a lot of things work as planned.
(These child-builder appearing are "at long last!" -- these methods were known to be needed for some time now, but I'd been intentionally been pushing off the implementation of it until we finally reached some *other* piece of functionality that would depend on it and force the issue.  Finally, that's happened: that issue is unmarshalling into natively-typed codegenerated nodes, and that's now.  Woo!)
(Though the current focus of this is for natively-typed codegen'd nodes, if we put further effort into reflective-bind node implementations, they'll also lean heavily on these child-builder-getters for internally …
=> Child-builder recursion; and typed unmarshal over codegen native structs.

traversal/selector/builder/builder.go, traversal/selector/builder/builder_test.go, traversal/selector/exploreRecursive.go, traversal/selector/exploreRecursive_test.go, traversal/selector/fieldKeys.go, traversal/walk_test.go
Support https://github.com/ipld/specs/pull/207, now merged
In explore recursive, internally use a depth parameter and a hasDepth boolean. For limit type depth, depth = depth limit & hasDepth = true. For limit type none, depth = n/a & hasDepth = false
=> feat(selectors): support union limit type

schema/gen/go/genCommon.go, schema/gen/go/genCommonNb.go, schema/gen/go/genKindBytes.go, schema/gen/go/genKindBytesBuilder.go, schema/gen/go/genKindInt.go, schema/gen/go/genKindIntBuilder.go, schema/gen/go/genKindLink.go, schema/gen/go/genKindLinkBuilder.go, schema/gen/go/genKindList.go, schema/gen/go/genKindListBuilder.go, schema/gen/go/gen_test.go, schema/tmpBuilders.go
Totally selfish, I want to try to code gen protobuf nodes. I needed Link, Bytes, and Int to make it work.
You do not need merge this. At the same time, it seemed like a lot of code busy work that might save you time. I get the sense you are still iterating on the core abstractions and focusing on the hardest part, but if this saves you time once you get there, here you go.
=> FYC: add int, bytes, and link types to code-gen

must/must.go
Because golang supports implied destructuring of multiple-return functions into arguments for another funtion of matching arity, we can build some interesting API usage patterns to help with chaining/pointfree styles of usage.
For example, the `must.Node` function in this package can be used like this:
```
must.Node(SomeNodeBuilder{}.CreateString("a"))
```
Despite the fact the `CreateString` in this example returns `(ipld.Node, error)`, the `must.Node` call that wraps it returns *only* `ipld.Node`... so you can continue to linearly chain more method calls after it!
=> must: an alternative mechanism for fluent calls.

schema/gen/go/HACKME.md, schema/gen/go/gen.go, schema/gen/go/genMinima.go, schema/gen/go/gen_test.go
I'm using some early code gen in https://github.com/ipld/go-ipld-prime-proto (DagPB for go-ipld-prime!).
Making these methods public seemed like the least intrusive way to allow a preliminary method for generating code outside this module.  I'm not asking for stability on these APIs -- just a commit in master, that go-ipld-prime-proto can be built on till things stabilize (and then it would be updated obviously)
=> feat(schema/gen): make emit methods public

schema/gen/go/genKindListNode.go, schema/gen/go/genKindStructNode.go
Map/List should return an actual node type, not a pointer to a node. Otherwise, breaks when nested
in other map/list type.
We use a pointer to a node when we're building nodes, for maps (so we can mod it easily I assume). However, when we actually build it, we should dereference it -- because that's the type anyone using the node expects-- and in fact things will error if you build a map inside a map.
=> fix(schema/gen): return value not reference

path.go, pathSegment.go, path_test.go
Several significant clarifications to Path docs.
Primarily, being committal and direct about how special values, erm... *aren't* -- namely, "/" is a valid segment, and so is empty string -- and confessing how much tricky work that makes.
Several methods are now more upfront about how much they *do not do good things* on such values.  I'd like to fix these methods, but to do that, we should formally specify an escaping system and canonical string encoding for paths.  That work should start in the IPLD Specs repo, and involve fixtures.  Once that is tackled, I will (very!) gladly start fixing these methods to operate accordingly, and get rid of all the sharp-edges warnings.
Several methods also now include comments about whether they will enforce string character encoding or normalization …
=> Path clarifications

codecov.yml
I have little idea what this did,
and found its visualizations more confusing than useful.
I also have little fondness for cloud-based services of this kind
if they don't have any useful contribution to localhost development,
and I think we can easily look at this file and see that it said
nothing of use.
Per the advice of https://github.com/ipld/go-ipld-prime/pull/49#issuecomment-595552836 ...
RIP IT OUT
=> Drop code coverage bot config.

traversal/fns.go, traversal/walk.go
`traversal.SkipMe` can now be used to control walks.
Looks (and is) simple, but enables a lot.  This is the key feature to make it possible for link loader logic to do things like skip already-seen blocks, among other applications.
=> traversal.SkipMe feature

codec/dagcbor/marshal.go, codec/dagcbor/roundtrip_test.go
This bug manifested as an issue in Graphsync's IPLD prime upgrade where it appeared the created blockchain structure was not working. As it turns out, the issue was not the structure of nodes created but encode/decode from CBOR. I tracked it to an ErrInvalidMultibase error in decode, but eventually figured out the error was on a node that was created as bytes. Eventually, I noticed that during the NodeAssembler upgrade, we switched from marshall using a local token variable at each recursive level to a single token variable passed down the recursion tree as a pointer. Eventually, that led me to realize that once a link was encountered during traverse, tk.Tagged was set true and never unset (along with tk.Tag = linkTag). If there was a subsequent Bytes node encountered, it was written as a …
=> Fix marshalling error

nodeBuilder.go, schema/errors.go, schema/gen/go/HACKME_wip.md, schema/gen/go/README.md, schema/gen/go/adjunctCfg.go, schema/gen/go/genStruct.go, schema/gen/go/genStructReprMap.go, schema/gen/go/genUnion.go, schema/gen/go/genUnionReprKeyed.go, schema/gen/go/generate.go, schema/gen/go/genpartsStrictoid.go, schema/gen/go/templateUtil.go, schema/gen/go/testUnions_test.go, schema/tmpBuilders.go, schema/type.go, schema/typeMethods.go
Unions!  :tada: 
Unions were one of the last major groups of functionality in the feature table that we had *no* codegen implementations of yet, so this is pretty huge news overall.  Nothing broke; no abstractions shattered.  Whew.  (Enums are the only thing left, but those are pretty easy-peasy.  Unions, being a container/recursive type kind rather than a leaf, were pretty heavy-duty.)
We have two things here, as always: the "type-level" and the "representation-level" implementations of the Node and NodeAssembler interfaces.
- the "type-level" Node for a Union always acts like a map, and the keys are always the names of the member Type.
- the "representation-level" Node behavior may (of course) vary, but for "keyed" representations... it's roughly the same as the type-level semantics; …
=> Codegen of unions, and their keyed representations

schema/gen/go/_demo/omg-schemas/schemaschema_test.go
Self-hosting gen of the schema-schema!
... Mostly.  I've taken the opportunity to make a few tweaks to naming as I went, and there are a few other minor divergences:
- A few cases use keyed unions when they should be kinded; this is a significant todo.
- A few cases use keyed unions where the schema-schema declaration says they should use inline representations!
- In these, I've come to believe the schema-schema made a mistake; we probably will update it.
- We're still making little hacks to dodge the current placeholder typeinfo's lack of support for inline defns.
- ...but this is purely a problem of the placeholder typeinfo structures, and can disappear the instant we replace them.
And he whole specification is still written in code: the 'SpawnFoo' placeholder methods are in heavy use. …
=> Self-hosting gen of the schema-schema.

node/gendemo/tMsg3.go, schema/errors.go, schema/gen/go/README.md, schema/gen/go/genStruct.go, schema/gen/go/genStructReprMap.go, schema/gen/go/genStructReprTuple.go, schema/gen/go/genUnion.go, schema/gen/go/genUnionReprKeyed.go, schema/gen/go/generate.go, schema/gen/go/testStructReprTuple_test.go, schema/tmpBuilders.go
Codegen now supports structs with a tuple representation strategy -- that is, a representation that's a list, where the position alone corresponds to each field in the struct, and thus to the expected type and the meaning of the value.
=> Struct tuple representation codegen

schema/gen/go/HACKME_dry.md, schema/gen/go/README.md, schema/gen/go/genUnionReprKinded.go, schema/gen/go/generate.go, schema/gen/go/templateUtil.go, schema/tmpBuilders.go, schema/type.go, schema/typeMethods.go
Kinded unions are now generateable!
My favorite part of the diff is quite simply the feature table change:
```diff
-| ... kinded representation      |     ✘     |     ✘    |
+| ... kinded representation      |     ✔     |     ✔    |
```
Kinded unions are pretty neat to have, because between them and keyed unions, we can do most of the stuff that's Interesting.  (Substituting keyed unions for other strategies as a placeholder during prototyping systems is generally fine (in addition to the fact we simply use them the most in new designs anyway); kinded unions less so, because they change the topology of the document rather noticeably.)  I've started prototyping a bunch of stuff using them.
---
It has turned out we can also now generate any "Any" type using kinded unions and really no …
=> Kinded union gen

codec/jst/jst_test.go, codec/jst/util.go, errors.go
There were two vet errors in two packages containing tests, resulting in
'go test' erroring out before any tests were run. Both were due to the
same reason - an Error method that ends up calling itself forever, thus
a panic.
While at it, 'gofmt -w -s' everything, which removes a redundant type.
=> all: make 'go test ./...' pass on Go 1.15

codec/dagcbor/marshal.go, codec/dagjson/marshal.go, linking/cid/cidLink.go
As spotted by staticcheck. While at it, remove punctuation from another
couple of errors, as per
https://github.com/golang/go/wiki/CodeReviewComments#error-strings:
Error strings should not be capitalized (unless beginning with
proper nouns or acronyms) or end with punctuation, since they
are usually printed following other context.
=> linking/cid: check a previously unused error

schema/gen/go/genUnion.go, schema/gen/go/genUnionReprKeyed.go, schema/gen/go/genUnionReprKinded.go, schema/gen/go/testUnionsKinded_test.go, schema/gen/go/testUnions_test.go
Update the tests targeting codegen'd unions to use the new test helper system introduced in https://github.com/ipld/go-ipld-prime/pull/66 .
The increased coverage found an infinite loop in iterators, so the fix for this is included.  Similarly, a bug in the assembler's reset mechanism was found, and is fixed.
With these two fixes, I'm also coincidentally able now able to use codegen'd unions in some pretty interesting larger demos without incident.  More news on that shortly ;)
=> Update tests for unions; several fixes

codec/dagcbor/roundtripCidlink_test.go, codec/dagcbor/roundtrip_test.go, codec/dagjson/roundtripCidlink_test.go, codec/dagjson/roundtrip_test.go, codec/jst/demo/main.go, codec/jst/jst_test.go, exampleLinking_test.go, examples_test.go, node/gendemo/hax_test.go, node/tests/marshalBenchmarks.go, node/tests/unmarshalBenchmarks.go, node/tests/util.go, schema/gen/go/testcase_test.go, traversal/focus_test.go, traversal/selector/exploreRecursive_test.go, traversal/walk_test.go
Buffers are not a good option for tests if the other side expects a
reader. Otherwise, the code being tested could build assumptions around
the reader stream being a single contiguous chunk of bytes, such as:
_ = r.(*bytes.Buffer).Bytes()
This kind of hack might seem unlikely, but it's an easy mistake to make,
especially with APIs like fmt which automatically call String methods.
With bytes.Reader and strings.Reader, the types are much more
restricted, so the tests need to be more faithful.
=> all: don't use buffers where readers suffice

.github/workflows/test.yml, schema/gen/go/testLists_test.go, schema/gen/go/testMaps_test.go, schema/gen/go/testString_test.go, schema/gen/go/testStructNesting_test.go, schema/gen/go/testStructReprStringjoin_test.go, schema/gen/go/testStructReprTuple_test.go, schema/gen/go/testStructsContainingMaybe_test.go, schema/gen/go/testUnionsKinded_test.go, schema/gen/go/testUnions_test.go
They do quite a lot of work, including setting up a type system,
generating Go code, and building it.
This package is by far the slowest to test. On a warm cache, 'go test
-count=1 ./...' shows all packages under 0.2s, while this one sits at
~1.5s.
1.5s is not unreasonable with a warm cache, but we can bring that down
to 0.6s on my quad-core laptop by just making all tests parallel. Note
that sub-tests aren't parallel for now, since there are multiple layers
of them and I'm not sure I even follow what's going on.
=> WIP: schema/gen/go: make all top-level tests parallel

fluent/doc.go, fluent/reflect.go, fluent/reflect_test.go
This diff introduces new convenience functions into the fluent package which create Nodes by looking at data in golang native structures and flipping them into IPLD data model.
These are probably not _fast_, but they might be handy in debugging, putting together quick hacks, or simply for demos.
=> Introduce fluent.Reflect convenience functions.

schema/gen/go/genLink.go
Should fix https://github.com/ipld/go-ipld-prime/issues/90 .
=> Codegen for links should emit the methods to conform to the schema.TypedLinkNode interface where applicable.

codec/dagcbor/unmarshal.go
This is an alternative fix for https://github.com/ipld/go-ipld-prime/pull/82 .
This diff keeps a single resource budget throughout the entire parse and unmarshal process, decrementing it as resources are consumed.  Where possible, it also checks if a length header suggests the resource limit will be exhausted within the next stretch.
This does not yet include a configuration mechanism, but I've set it to "around 10 megs" for now, which is probably a reasonable safe number to roll out today as a default (considering that in many projects that use IPLD, libp2p is also in play, which sets much lower limits for serial message size already).  I'd certainly like to make it properly configurable, but perhaps that can be explored later.
=> Implement resource budgets in dagcbor parsing.

schema/gen/go/genStructReprTuple.go, schema/gen/go/genpartsMinima.go
Make error info available when tuples process data that is too long.
(Should fix https://github.com/ipld/go-ipld-prime/issues/97 .)
This requires introducing an error-carrying NodeAssembler,
because the AssembleValue methods don't have the ability to return errors themselves.
AssembleValue methods have not needed to return errors before!
Most lists don't have any reason to error: out of our whole system,
it's only struct-with-tuple-representation that can have errors here,
due to tuples having length limits.
AssembleValue for maps doesn't have a similar challenge either,
because key invalidity can always be indicated by errors returned from
the key assembly process.
I'm not a big fan of this diff -- error carrying thunks like this are
ugly to write and they're also pretty ugly to use -- …
=> codegen: make error info available when tuples process data that is too long.

schema/gen/go/_demo/omg-schemas/schemaschema_test.go, schema/gen/go/genList.go, schema/gen/go/genMap.go, schema/gen/go/genStruct.go
Bulk PR for a bunch of individually minor codegen improvements.
- More Lookup methods on typed maps which are only available when concrete types are known, but keep you in the realm of concrete types.
- New Iterators on typed maps with the same concreteness.
- More Lookup methods on typed lists with ... you get the idea.  Concreteness.  Less casting in your future when you use these.
- New Iterators on typed lists with the same concreteness.
- Some other misc bits, like: the schema-schema demo had forgotten "stringprefix" in union strategies, and now it has them.
It's basically a laundry list of small quality-of-life things that I encountered today while working on other things that consume codegen'd code.
(These aren't particularly interesting, so I'll probably merge this with or without …
=> Codegen various improvements

traversal/select_links.go, traversal/select_links_test.go
Like it says on the tin.
This is just a quick, simple, handy function to have on hand.
=> Introduce traversal function that selects links out of a tree.

adl/rot13adl/example_test.go, adl/rot13adl/rot13logic.go, adl/rot13adl/rot13node.go, adl/rot13adl/rot13node_test.go, adl/rot13adl/rot13prototypes.go, adl/rot13adl/rot13reification.go, adl/rot13adl/rot13substrate.go
I've been working on an ADL implementation for demo purposes -- a "rot13" ADL: it treats the raw data as a rot13 string, and rotates it for the high level view.  This is a pretty useless gadget... except it's so simple that I'm hoping it will make a good piece of example code, to help show what ADLs do and how their interfaces should work.  The goal of this is to be able to hand a link to this package to someone wanting to implement a new ADL, and have them get a lot of useful pointers about how to start implementing their own ideas in a new package of their own.
The package docs in the diff body say more about the publicly exported interfaces and what kind of logical contracts we expect from them, but in summary:
- there are high-level `Node`/`NodeBuilder`/`NodePrototype` types, which …
=> Add a demo ADL (rot13adl)

codec/api.go, codec/codectools/token.go, codec/codectools/token_consumers.go, codec/codectools/token_consumers_test.go, codec/codectools/token_producers.go, codec/codectools/token_producers_test.go, codec/codectools/token_test.go, codec/codectools/token_util.go
The tokenization system may look familiar to refmt's tokens -- and
indeed it surely is inspired by and in the same pattern -- but it
hews a fair bit closer to the IPLD Data Model definitions of kinds,
and it also includes links as a token kind.  Presense of link as
a token kind means if we build codecs around these, the handling
of links will be better and most consistently abstracted (the
current dagjson and dagcbor implementations are instructive for what
an odd mess it is when you have most of the tokenization happen
before you get to the level that figures out links; I think we can
improve on that code greatly by moving the barriers around a bit).
I made both all-at-once and pumpable versions of both the token
producers and the token consumers.  Each are useful in different
scenarios. …
=> Fresh take on codec APIs, and some tokenization utilities.

errors.go, schema/gen/go/genStruct.go, schema/gen/go/testStructsContainingMaybe_test.go
Check that all struct fields that are required have been set when Build'ing the Node.
=> Validate struct builder sufficiency

schema/gen/go/adjunctCfg.go, schema/gen/go/genList.go, schema/gen/go/genMap.go, schema/gen/go/genStruct.go, schema/gen/go/genUnion.go, schema/gen/go/generate.go, schema/gen/go/generators.go, schema/gen/go/genpartsCommon.go, schema/gen/go/genpartsMinima.go, schema/gen/go/templateUtil.go
Rearrange codegen output into finite number of files.
Also, emit some comments around the type definitions.
The old file layout is still available, but renamed to GenerateSplayed.  It will probably be removed in the future.  (Maybe it should be removed now, for that matter.)
All the files produced now match the pattern "`ipldsch.*.gen.go`".  There's file for the common bits that need to appear in every codegen output package; one file for all the type definitions, including the type/prototype table (I figure this is what a developer will hit most often during quick reference); and one file for everything else (including the MaybeT types, the Node implementations, the NodeAssembler implementations, and all that again for the representation level).
This could be a resolution for …
=> Codegen output rearrange

schema/gen/go/externUtil.go, schema/gen/go/generate.go
This change will look at the destination package that codegen is being built into, and will skip generation of types that are already declared by files not prefixed with `ipldsch_`.
This isn't the cleanest escape-hatch, but it's a start.
=> Support overriden types

codec/codectools/scratch/reader.go, codec/codectools/scratch/reader_test.go, codec/dagjson2/doc.go, codec/dagjson2/json_unmarshaller.go, codec/dagjson2/token/json_decode.go, codec/dagjson2/token/json_decode_number.go, codec/dagjson2/token/json_decode_string.go, codec/dagjson2/token/json_decode_string_test.go, codec/dagjson2/token/json_decode_test.go
Alright, this is kind of a lot.
This introduces some new decoders.  I'll probably keep appending to this PR for a while until it includes encoders as well.
The aim is to, by the end of this revamp, be able to do something about the linking API situation (https://github.com/ipld/go-ipld-prime/issues/55),
and in particular, start approaching the API drafts in https://gist.github.com/warpfork/c0200cc4d99ee36ba5ce5a612f1d1a22 ... which involves normalizing the codec interfaces a bit better than they currently are.
While we're at it... why not fix everything?  Scope control is for chumps, amiright?
(I'll regret saying that, of course.  I already do.  But, the code that bites off a lot of fixes at once is already brewing here, so, here we go...)
So: performance, API consistency, better …
=> Codec revamp

CHANGELOG.md, schema/gen/go/genStructReprMap.go, schema/gen/go/testStruct_test.go, schema/gen/go/testStructsContainingMaybe_test.go, schema/typeMethods.go
The NodeAssembler for structs with map representations now correctly validates all non-optional fields are present.
This continues what https://github.com/ipld/go-ipld-prime/pull/111/ did and adds the same logic to the map representation.  The actual state tracking works the same way (and was mostly already there).
Rearranged the tests slightly.
Made error messages include both field name and serial key when they differ due to a rename directive.  (It's possible this error would get nicer if it used a list of StructField instead of just strings, but it would also get more complicated.  It may be worth revisiting this later, but for now it seems sufficient.)
=> codegen: assembler for struct with map representation validates all non-optional fields are present

path.go, traversal/common.go, traversal/focus.go, traversal/focus_test.go
`traversal.FocusedTransform` is now available.  It takes a starting Node, a Path, and a TransformFn (which is essentially just a function from Node to Node), and uses those instructions to build a new Node tree with the transform applied at the given path.
Like all the other `traversal.*` functions, it carries a `traversal.Progress` object around, which you can use in the TransformFn to see where you are, or to do continued traversals or transformations at deeper levels of the data while keeping a coherent track of overall position, etc.
This works even if the Path happens to cross links!  If you've configured enough Loader and Storer functions in the `traversal.Config`, any links crossed will be automatically loaded, the transform will continue inside, and when the transform is complete, …
=> Implement traversal.FocusedTransform.

node/mixins/delim.go, schema/gen/go/README.md, schema/gen/go/genUnion.go, schema/gen/go/genUnionReprStringprefix.go, schema/gen/go/generate.go, schema/gen/go/testUnionsStringprefix_test.go, schema/tmpBuilders.go, schema/type.go, schema/typeMethods.go
=> gengo: support for unions with stringprefix representation.

fluent/quip/operations.go, fluent/quip/quip.go, fluent/quip/quip_bench_test.go, fluent/quip/quip_example_test.go
I developed a new pattern for building IPLD structures.  This started as a little experiment, but worked so dang well I instantly want to ship it.
The basic idea is that every function in the package takes an `*error` as its first parameter, and gathers any errors during the function's operation in there, instead of returning them.  If the `*error` is already non-nil, it just returns without doing anything.  This lets you write very linear code without a lot of fuss, and tends to "do the right thing" in over all flow control.
A function that's the equivalent of each of the methods on `NodeAssembler` exists.  (I've also sprinkled in a few other useful ones like "CopyRange" for lists.)  These generally take a `NodeAssembler` to work on as a parameter.  For those functions that work on …
=> Introduce 'quip' data building helpers.

node/gendemo/ipldsch_satisfaction.go, schema/dmt/ipldsch_satisfaction.go, schema/gen/go/genStruct.go, schema/gen/go/genStructReprMap.go, schema/gen/go/genUnion.go, schema/gen/go/genUnionReprKeyed.go, schema/gen/go/genUnionReprKinded.go
In particular, this removes ~50 out of the 2.7k warnings in 'go vet
./...' in this repository. Mainly, the "unreachable code" ones.
This was caused by edge cases in some of the generated code which caused
an unconditional return or panic statement to be followed by other code.
Fix all of them with a bit more template logic.
Some of the Next methods go a bit further. If they serve no purpose as
the switch has no cases to be matched, just unconditionally return an
error. In the future we can perhaps reuse a single function for that.
Finally, I was having a hard time actually following the logic in
kindedUnionNodeAssemblerMethodTemplateMunge, so I've indented the code a
bit to follow the template logic and scoping.
These changes move us towards pleasing vet, which is nice, but also make
the …
=> schema/gen/go: please vet a bit more

errors.go
%q is superior to the manually quoted "%s", since it will properly
escape the inner string when quoting. For example:
"here goes a double quote: \" "
Even if this does not matter in practice, using %q is easier too.
=> use %q in error strings

schema/gen/go/testEngine_test.go
Practically every subtest ends up at 7 or so levels of names, like:
TestMapsContainingMaybe/maybe-using-ptr/generate/compile/bhvtest/non-nullable/typed-create
However, note that the "generate" and "compile" levels are always there,
so their presence just adds verbosity in the output and makes the
developer's life more difficult.
Extremely nested sub-tests are already rare, so at least we can just
keep the components that add useful information in the output.
"bhvtest" is also pretty redundant, but that one actually matters - its
subtest can be skipped depending on build tags.
=> schema/gen/go: remove two common subtest levels

node/basic/list.go, node/basic/map.go, node/gendemo/ipldsch_satisfaction.go, schema/dmt/ipldsch_satisfaction.go, schema/dmt/ipldsch_types.go, schema/gen/go/genList.go, schema/gen/go/genMap.go, schema/gen/go/genStruct.go, schema/gen/go/genStructReprMap.go, schema/gen/go/genStructReprTuple.go, schema/gen/go/genUnion.go, schema/gen/go/genUnionReprKeyed.go, schema/gen/go/genpartsMap.go
In particular, use keys for ipld error structs. These have one field, so
the changes are pretty simple.
Reduces 'go vet ./...' from 2647 lines of output to 2365.
Updates #102.
=> schema/gen/go: prevent some unkeyed literal vet errors

fluent/bench_test.go, fluent/qp/example_test.go, fluent/qp/qp.go
This is what I came up with, building on top of Eric's quip. I don't
want to waste too much time naming this, and I like two-letter package
names in place of dot-imports, so "qp" seems good enough for now. They
are the "strong" consonants when one says "Quick iPld".
First, move the benchmarks comparing all fluent packages to the root
fluent package, to keep things a bit more tidy.
Second, make all the benchmarks report their allocation stats, without
having to always remember to use the -benchmem flag.
Third, add a qp benchmark.
Fourth, notice a couple of potential bugs in the quip benchmarks, and
add TODOs for them.
Finally, add the qp API. It differs from quip in a few external ways:
1) No error pointers. Instead, it uses panics which are recovered at the
top-level API layer. This …
=> fluent: add qp, a different spin on quip

fluent/qp/qp.go
I started rewriting the "getting started" Go guide to use fluent/qp
instead of fluent, but I'm missing some of the helpers since the guide
uses links, among others.
This is largely copy-pasted, but there are just a handful of types and
it's barely a dozen lines per type. A generator is not worth it for 100
lines of code that will rarely ever need to change.
=> fluent/qp: finish writing all data model helpers

schema/gen/go/testEngine_disabled_test.go, schema/gen/go/testEngine_nocgo_test.go, schema/gen/go/testEngine_plugin_test.go, schema/gen/go/testEngine_test.go
This means we no longer clutter the repository with lots of files, even
if they are git-ignored. It's always a bit of a red flag when you run
"go test ./..." and the result is a bunch of leftover files.
We still want to keep the files around, for the sake of Go's build
cache. And we still want their paths to be static between "go test"
runs. So put them in a static dir under os.TempDir.
This does mean that concurrent runs of these tests will likely not work
well. I don't imagine that's going to be a problem anytime soon, though.
If it really becomes a problem in the future, we could figure something
out like grabbing a file lock for the directory.
The idea behind using os.TempDir is that it will likely remain in place
between a number of "go test" runs within a hacking session, but it …
=> schema/gen/go: cache genned code in os.TempDir

node.go
As a method superset of Node, with the Substrate method added on top.
This way, we can generally say that any ADL implementation should
include this method to allow for easy encoding over the wire.
Reify, the opposite of Substrate, is notably missing here. This is
because it's generally a top-level function, not a method. We might want
to rethink this disparity in the future.
=> add an ADL interface type

codec/raw/codec.go, codec/raw/codec_test.go, go.mod, go.sum
=> codec/raw: implement the raw codec

adl/rot13adl/example_test.go, codec/dagjson/marshal.go, codec/dagjson/multicodec.go, codec/dagjson/unmarshal.go, codec/json/multicodec.go, codec/jst/jst.go, schema/gen/go/testcase_test.go, schema/schema2/typesystem_test.go
Would this acceptable as a first-pass at the 'non-dag' json?
=> add non-dag json codec

codec/cbor/multicodec.go, codec/dagcbor/marshal.go, codec/dagcbor/multicodec.go, codec/dagcbor/unmarshal.go
This parallels #152 but for cbor.
=> implement non-dag cbor codec

linking.go, linksystem.go
When the underlying storage system is local, we may want to skip hash on read to increase performance. This adds a boolean value that tells the LinkSystem to skip hash checking when loading nodes.
Extra bonus: this will be fine as an alternative to the bytesBuffer optimization!
=> Add option to tell link system storage is trusted and we can skip hash on read

adl/rot13adl/example_test.go, linking.go, linksystem.go
Proposal for how to integrate ADL creation into the LinkSystem loading process
Add an optional reifier into the link system process to create ADLs. The reason to do this is to capture the link
system itself when reification happens, in case it needs to be put into the node, which is often not
accessible by the time you have a node. 
Another alternative would be to make this specific to
selector traversal, similar to LinkNodePrototypeChooser
I actually left off Storage as a concern entirely. The simple version would be to just make a NodeSubstrater function with a shape like this:
```golang
type NodeSubstrater func(ipld.Node) (ipld.Node, error)
```
But in reality a Store operation on an ADL Node built with some kind of ADL builder (think HAMT) actually probably stores SEVERAL blocks. I'm …
=> feat(linksystem): add reification to LinkSystem

node/gendemo/gen.go, node/gendemo/ipldsch_satisfaction.go, schema/dmt/gen.go, schema/dmt/ipldsch_satisfaction.go, schema/gen/go/adjunctCfg.go
=> schema/gen/go: avoid Maybe pointers for small types

schema/gen/go/generate.go
=> schema/gen/go: batch file writes via a bytes.Buffer

node/gendemo/doc.go, schema/dmt/gen_trigger.go, schema/gen/go/generate.go
=> schema/gen/go: apply gofmt automatically

codec/dagjson/marshal.go, codec/dagjson/roundtripBytes_test.go, codec/dagjson/unmarshal.go
fix #165
The 'allowLinks' flag to `marshal`/`unmarshal` seems at this point to have extended past it's original name. Would happily take suggestions for a better a name.
=> Allow emitting & parsing of bytes per dagjson codec spec

multicodec/defaultRegistry.go, multicodec/registry.go
(This is a logical port of https://github.com/ipld/go-ipld-prime/pull/169 to follow https://github.com/ipld/go-ipld-prime/pull/172 .)
I've added more documentation -- particularly, cautionary notes on the package-scope functions which read the global shared state.
=> Add enumerate methods to the multicodec registries.

equal.go, equal_test.go, schema/gen/go/testLists_test.go, schema/gen/go/testMaps_test.go, schema/gen/go/testStructReprStringjoin_test.go, schema/gen/go/testStructReprTuple_test.go, schema/gen/go/testStruct_test.go
=> add DeepEqual and start using it in tests

node/bindnode/api.go, node/bindnode/node.go, schema/typedNode.go
=> schema: add TypedPrototype

node/basic/any.go, traversal/focus_test.go, traversal/walk_test.go
=> node/basic: add Chooser

adl/rot13adl/example_test.go, codec/dagjson/multicodec.go, codec/dagjson/roundtripBytes_test.go, codec/dagjson/roundtrip_test.go, examples_test.go, fluent/qp/example_test.go, node/bindnode/example_test.go, node/tests/testcase.go, schema/schema2/typesystem_test.go, traversal/focus_test.go
but .. this is only part of the story, because we still have map key ordering "problems"
=> Remove pretty-printing

codec/dagjson/marshal.go, codec/dagjson/multicodec.go, codec/dagjson/roundtripBytes_test.go, codec/dagjson/roundtripCidlink_test.go, codec/dagjson/roundtrip_test.go, codec/dagjson/unmarshal.go, codec/json/multicodec.go, codec/jst/jst.go, fluent/qp/example_test.go, node/bindnode/example_test.go, node/tests/schemaStructsContainingMaybe.go, node/tests/testcase.go, traversal/focus_test.go
Let me count the ways that you're going to hate this @warpfork ... but this is what everyone else has agreed the spec should do, it's what go-ipfs is doing with its existing encoding/json usage so existing test fixtures all make this assumption, and this opens the way to get some cross-impl test fixtures in place.
As for my impl, yeah .. that might take some finessing.
Builds on #202 so whitespace removal is in here already.
=> Sort map entries marshalling dag-json

node/bindnode/schema_test.go, node/tests/schema.go, node/tests/schemaLinks.go, schema/gen/go/genLink.go, schema/gen/go/testLinks_test.go
Found in https://github.com/ipfs/go-ipld-git/pull/46 integrating into go-ipfs
which wants to load typed nodes when it encounters typed links. It errors
because it's trying to load the typed node into the type of the typed link
rather than the referenced type.
https://github.com/ipfs/go-ipld-git/pull/46 currently has codegen using this branch and is now working in go-ipfs doing path traversals through nested linked objects 👌.
=> fix: typed links LinkTargetNodePrototype should return ReferencedType

traversal/selector/condition.go, traversal/selector/condition_test.go, traversal/selector/exploreRecursive.go, traversal/selector/exploreRecursive_test.go
allows selectors of the form:
```json
{
"R": {
"l": {
"none": 0
},
":>": {
"a": {
">": {
"@": {}
}
}
},
"!": {
"/": {
"/":"bafyreifepiu23okq5zuyvyhsoiazv2icw2van3s7ko6d3ixl5jx2yj2yhu"
}
}
}
}
```
=> Add link conditions for 'stop-at' expression in ExploreRecursive selector

codec/dagcbor/unmarshal.go, codec/dagjson/unmarshal.go
For blocks that are simply "null":
* dag-cbor: `0xf6`
* dag-json: `null`
=> Allow parsing of single Null tokens from refmt

CHANGELOG.md, codec/README.md, codec/api.go, codec/cbor/multicodec.go, codec/dagcbor/marshal.go, codec/dagcbor/multicodec.go, codec/dagcbor/unmarshal.go, codec/dagjson/marshal.go, codec/dagjson/multicodec.go, codec/dagjson/unmarshal.go, codec/json/multicodec.go, codec/marshal.go, codec/unmarshal.go, node/tests/testcase.go
No breaking changes.  In fact I think this should be behaviorally identical to before, despite the size of the diff. There are some functions that are explicitly marked as deprecated now, but I am not removing them in this diff.
One exception: some struct names did change.  However, these have not been included in any tagged release so far, so I believe changing them now is still pretty fair game, and the number of affected people should be slim to none.
The main source of changes is pushing towards nomenclature consistency, which is described in the new readme file also included the diff.
=> codecs: more docs, a terminology guide, consistency in options.

node/bindnode/api.go, node/bindnode/example_test.go, node/bindnode/infer.go, node/bindnode/node.go, node/bindnode/repr.go
=> node/bindnode: redesign the shape of unions in Go

node/bindnode/node.go, node/bindnode/repr.go, schema/tmpBuilders.go
A variety of error message improvements and polish as diffs.
I'm trying to just track these things and do target-of-opportunity work as I try to be a downstream user.  The commit messages still say what and why, but the focus is... whatever I hit. :)
=> Bindnode fixes of opportunity

traversal/selector/selector.go
Writing selector implementations is hard.  The previous docs were very skeletal.  This should provide more knowledge about the phases and what's going on with the different functions a selector needs to implement.
=> selector: Improve docs for implementors.

.gitmodules, go.mod, go.sum, traversal/selector/spec_test.go
This has been LONG overdue.
It depends on a matching PR to the specs, which is:
https://github.com/ipld/ipld/pull/130 .
It adds the specs+docs repo as a git submodule.
(This may be tetchy to some people, but they Solve Problems.)
If you don't check out the submodule, these tests are just skipped.
It adds github.com/warpfork/go-testmark as a new dependency.
This is what parses the fixture format.  It's nothing special;
the fixture format is also... markdown.  This parser just gives us
a good combination of human readability and machine processability.
=> selector: add tests which are driven by language-agnostic spec fixtures.

codecHelpers.go, codecHelpers_test.go, schema/tmpBuilders.go
Add new helper methods that shorten up the number of keystrokes needed for common operations related to encoding and decoding.
These are added in the root `ipld` package, where new users of the library should find them quickly and easily.  (This was made possible by #228 .)
Many common operations are available, but of course not all of them -- for example, if one wants to control a NodeBuilder manually and use its Reset features for allocation avoidance on repeated use, you'd still have to dive deeper and these facades won't help you.  *But*, at the same time, the sheer existence of these facades -- and their copious documentation about subjects exactly like that one! -- means users should find that easier than ever to learn how to do, if it becomes desirable to them to go there.
Some of …
=> helper methods for encoding and decoding

codecHelpers.go, datamodel/errors.go, node/bindnode/node.go, node/bindnode/repr.go, schema/tmpBuilders.go, schema/typeMethods.go
Like it says on the tin.
Details in commit messages.
=> Bindnode fixes continued

node/bindnode/repr.go, node/tests/schemaStructReprStringjoin.go
In the case of an empty string as the first field, the buffer length
is not a valid proxy for whether we're on the first field or not.
This means if we have some type like:
`type Foo struct {a String; b String} representation stringjoin(":")`,
and the value of it is `{"", "b"}`, then the string of that
should still be ":b".
Before this fix, it would incorrectly be emitted as "b" (no joiner),
which would not round-trip.
=> bindnode: fix for stringjoin struct emission when first field is the empty string

printer/doc.go, printer/printer.go, printer/printer_test.go
I've started developing a `printer` feature, which provides a human-readable debugging output describing a tree of nodes.
This is an answer to https://github.com/ipld/go-ipld-prime/issues/88 .
- :heavy_check_mark: It's reasonably human readable, and rich in information.
- :heavy_check_mark: It can describe typed or untyped data, or a mixture of it.
- :heavy_check_mark: Everything works generically over the `datamodel.Node` interface, and feature-detects `schema.TypedNode` as appropriate.
- :heavy_check_mark: No additional methods are needed from nodes.
- :heavy_check_mark: There are a number of configuration options already (and probably more are desired).
- :non-potable_water: Nongoal: it's not a codec.  It's not intended to be parsable!  (This is important: I want this to provide _more_ …
=> Printer feature

traversal/focus.go, traversal/selector/exploreFields.go, traversal/selector/exploreUnion.go, traversal/walk.go
fix #58 
Savor the sweet joy of using go >= 1.13
- Replace some %s's with %w's in calls to fmt.Errorf
- The one reason this is actually nice is that you can run errors.Is against the return value of a selector traversal or focus to compare against an error returned from a block load
=> Cleanup error wrapping in traversal package

traversal/selector/parse/selector_parse.go
Ref: https://github.com/ipld/go-ipld-prime/issues/236
The selector.Selector type used for these selector variants are not useful if
you're interacting with an API that wants `datamodel.Node` selector forms.
Rather than trying to re-use builder.SelectorSpec here, just return the
`datamodel.Node` form since it's trivial to compile the selector for ourselves
on demand.
I considered returning a `builder.SelectorSpec` but `Selector()` on it has an `error` return which is unnecessary for this use since we're checking comparability here. And #236 suggests that users shouldn't be interacting with `selector.Selector` anyway so let's just go with the DMT here eh?
I'd also vote for removing `ParseAndCompileJSONSelector` completely too if this is the course of action we want to take with this API and …
=> Use datamodel.Node for "Common" selector variants

traversal/fns.go, traversal/focus.go, traversal/walk.go, traversal/walk_test.go
This patch adds budgets to traversals.  Setting a budget allows you to make a traversal halt and return within a fixed number of steps.
It's optional, and currently not on by default, but easy to set.
Budgets can be set in terms of either number of nodes visited, or number of links loaded.
A few other minor target-of-opportunity improvements to internal documentation are included, while I was passing through.
=> traversal: implement monotonically decrementing budgets.

datamodel/equal.go, datamodel/equal_test.go, node/bindnode/node.go, node/bindnode/schema_test.go, node/tests/testcase.go, schema/gen/go/genUnion.go, schema/gen/go/genUnionReprKeyed.go
Increase the coverage produced by the schema test suites markedly, fixing a few old todos in the test system for typed nodes.
The additional exercise picks up some bugs in the codegen for unions.
(This was also reported by Adin, and I think possibly by Ian earlier,
though I only got around to reproducing it fully now.)  Those bugs --
off-by-ones; uuf -- are now fixed.
Some todos were encountered in bindnode by the new coverage too.
Only one thing.  But it's a bit more than I knew how to fix in one
sitting, so I've made that test skipped for now, hopefully to be
fixed soon.
Some error messages that confused me along the way are tweaked.
The datamodel.DeepEquals method is slightly less fragile on nils.
=> schema,tests,gen/go: more tests, gen union fixes.

datamodel/copy.go, datamodel/nodeBuilder.go
Revisited the docs on the NodeAssembler interface, and described `AssignNode`'s contract and purpose better.
Also created a `datamodel.Copy` function.  This is related because just having that code gave me something to refer to which helped further clarify `AssignNode`.  (We should also probably start calling this function from codegen output, and perhaps other places, where similar logic is currently probably repeated, but I've left that out of this diff for now.)
=> Improve docs for AssignNode; and datamodel.Copy function.

node/tests/listSpecs.go, node/tests/mapSpecs.go, node/tests/schemaLinks.go, node/tests/schemaLists.go, node/tests/schemaMaps.go, node/tests/schemaScalars.go, node/tests/schemaStruct.go, node/tests/schemaStructReprStringjoin.go, node/tests/schemaStructReprTuple.go, node/tests/stringSpecs.go, node/tests/testcase.go
Port the tests in `node` package to quicktest; use:
- `qt.Assert` for `wish.Require`
- `qt.IsTrue` for ShouldEqual` over `true`
- `qt.IsFalse` for `ShouldEqual` over `false`
Port `closeEnough` Wish checker to its equivalent in quicktest.
Relates to:
- https://github.com/ipld/go-ipld-prime/issues/219
=> Port `node` package tests to quicktest

adl/rot13adl/rot13node_test.go
Port the tests in `adl` package to quicktest; use:
- `qt.Assert` for `wish.Require`
- `qt.IsNil` for `nil` with `ShouldEqual`
Relates to:
- https://github.com/ipld/go-ipld-prime/issues/219
=> Port `adl` package tests to quicktest

datamodel/path_test.go, go.mod
Port the tests in `datamodel` package to quicktest; use:
- `qt.CmpEquals` with custom `Exporter` that exports all fields for
`ShouldEqual` over `PathSegment`
Relates to:
- https://github.com/ipld/go-ipld-prime/issues/219
=> Port `datamodel` package tests to quicktest

fluent/fluentBuilder_test.go, fluent/fluentRecover_test.go, fluent/reflect_test.go
Port the tests in `fluent` package to quicktest; use:
- `qt.DeepEquals` for `ShouldEqual` over `[]byte` and `fluent.Error`
Relates to:
- https://github.com/ipld/go-ipld-prime/issues/219
=> Port `fluent` package tests to quicktest

README.md, README_migrationGuide.md
This document discusses interfaces, APIs, and concept names from other libraries in golang, and how they map to this library.
Some references are to storage systems which are appearing in https://github.com/ipld/go-ipld-prime/pull/279 .
=> readme: introduce a migration guide.

printer/printer.go, printer/printer_test.go
Implement textual representation for types `Link` and `[]byte` by
`printer`. Represent `Link` as its string value, and `[]byte` as its hex
encoded value.
=> Implement handling of `Link` and `[]byte` in `printer`

printer/printer.go, printer/printer_test.go
When the kind of `TypedNode` is a `Map`, the printer checks the type to
determine print complexity. Always use simple printing when type is
`nil`.
Relates to: #296
=> Gracefully handle `TypedNode` with `nil` type of kind `Map`

codec/cbor/roundtrip_test.go, codec/dagcbor/roundtripCidlink_test.go, codec/dagcbor/roundtrip_test.go, codec/dagcbor/unmarshal_test.go, codec/dagjson/roundtripBytes_test.go, codec/dagjson/roundtripCidlink_test.go, codec/dagjson/roundtrip_test.go, codec/raw/codec_test.go, node/mixins/delim_test.go, node/tests/checkers.go, node/tests/checkers_test.go, node/tests/schemaLists.go, node/tests/schemaMaps.go, node/tests/schemaStruct.go, node/tests/schemaStructReprStringjoin.go, node/tests/schemaStructReprTuple.go, node/tests/testcase.go
Implement `NodeContentEquals` quicktest checker that checks two given
nodes have equal content by comparing their printout using
`printer.Sprint`. This simplifies the tests that use
`datamode.DeepEqual` by performing an equivalent check while producing a
human-readable error when nodes are not equal. The naming for this check
is inspired by a similar equality check in quicktest, named
`ContentEquals`.
Port the tests in `codec` package to quicktest; use:
- `qt.Assert` for `wish.Require`
- `qt.IsTrue` for `ShouldEqual` over `true`
- `qt.IsFalse` for `ShouldEqual` over `false`
- `NodeContentEquals` for `ShouldEqual` over nodes
- `NodeContentEquals` for `datamodel.DeepEqual` over nodes
Update `NodeContentEquals` for …
=> Port `codec` package tests to quicktest

traversal/focus_test.go, traversal/select_links_test.go, traversal/selector/builder/builder_test.go, traversal/selector/condition_test.go, traversal/selector/exploreAll_test.go, traversal/selector/exploreFields_test.go, traversal/selector/exploreIndex_test.go, traversal/selector/exploreRange_test.go, traversal/selector/exploreRecursive_test.go, traversal/selector/exploreUnion_test.go, traversal/walk_test.go, traversal/walk_with_stop_test.go
Port the tests in `traversal` package to quicktest; use:
- `qt.Assert` for `wish.Require`
- `qt.IsTrue` for `ShouldEqual` over `true`
- `qt.IsFalse` for `ShouldEqual` over `false`
- `qt.HasLen` for `ShouldEqual` over slice length
- `qt.DeepEquals` for `ShouldEqual` over slices
- `CmpEquals` for `ShouldEqual` over types with unexported fields
excluding `datamodel.Node` with custom exporter to allow checking
of all unexported fields
- Defined checker once and reused across packages. Did not add
this to `node/tests` to avoid cycle package dependency.
- `nodetests.NodeContentEquals` over `datamodel.DeepEqual` and
`ShouldEqual` over `datamodel.Node`
Fixes #219
=> Port `traversal` package tests to quicktest

fluent/toInterfaceValue.go, fluent/toInterfaceValue_test.go
Fixes #178 
Does this seem like the general idea you were thinking of @mvdan? If so I'll add more documentation and maybe a couple more test cases.
=> Add toInterface

codec/dagcbor/unmarshal.go, codec/dagcbor/unmarshal_test.go
CBOR's "undefined" token -- byte 23; see https://datatracker.ietf.org/doc/html/rfc8949#section-5.7 or https://datatracker.ietf.org/doc/html/rfc8949#section-3.3 table 4 -- is not generally considered part of DAG-CBOR (which is generally a subset of CBOR).
However, it may be desirable to allow parsing data flagged as DAG-CBOR while coercing any "undefined" tokens to a "null", even if considering it noncanonical.
Because DAG-CBOR was not well specified early on, and because libraries existed for a considerable period of time which would readily emit data that we would not call DAG-CBOR, data exists in the wild which encoded these tokens, and links to them with an indicator that it's DAG-CBOR. We may wish to continue allowing these documents to be parsed.  (Related: …
=> dagcbor: coerce undef to null.

codec/dagjson/roundtripBytes_test.go, codec/dagjson/unmarshal.go
While we specify that the bytes field in dag-json is canonically the un-padded variant of the base64 encoding, there are existing records / dags created on versions of this library which did use padding. We should be able to parse these nodes.
=> Allow parsing padding in dag-json bytes fields

schema/typeMethods.go
(see commit messages - please do not squash)
=> node/bindnode: more minor improvements for graphsync

traversal/selector/exploreRecursive.go, traversal/selector/exploreRecursiveEdge.go, traversal/selector/selector.go, traversal/selector/spec_test.go, traversal/walk.go
See also the diff in the ipld/ipld repo for the new fixture,
which includes some explanation.
This would be a somewhat silly selector to write, but,
it doesn't seem to be something we should reject at compile time, either;
so, we must handle it gracefully.
Along the way, I documented some code that was sparse in comments.
I also added a shortcut to traversals so that a selector that
explicitly states it's not interested in anything (by returning a
non-nil but empty slice for its interests) is treated differently
than a nil return for interests (which means "I don't know; hit me
with everything you've got and lemme see").  This means that our
edge case here with edges (...heh) doesn't cause the traversal
to create an iterator that it doesn't really need, etc.
We turn out to need both that …
=> selectors: fix for edge case around recursion clauses with an immediate edge.

testutil/garbage/garbage.go, testutil/garbage/garbage_test.go
Bespoke garbage on a platter for all your testing and benchmarking needs. Modelled off https://github.com/rvagg/js-ipld-garbage, in fact it should produce roughly the same style of data.
It's not perfect, and it's not comprehensive, in fact it's garbage! But it's great for those tests where you need to throw random IPLD data at an API to see if it performs as you expect.
The API may need some critique, it feels comfortable to me but maybe it's too noisy with all the options and defaults.
A sampling of 10 pieces of garbage produced by this API with defaults:
```json
-0.815284567464555
[{"/":"baguqeerail77zjrvn52jkyv4wngs2x4sersmyf5xv3utayeme3x3tkn3ofpa"}]
{"-a`=D":{"/":{"bytes":"b0z9D15daxnyhWkKMwJHalyZYgBcZkApyJ+a2ofJNNVGrw"}},"LN_":{"-e@":{"[5B":{"/":"bafkreig6zjjdnwui43lfaugakyevsws7y3xv …
```
=> feat: add Garbage() Node generator

codec/dagcbor/marshal.go, codec/dagcbor/marshal_test.go, codec/dagcbor/roundtrip_test.go
For pre-allocation if it's going to be more efficient to walk the graph twice than have sloppy allocation during encode.
Seeing a need here: https://github.com/ipfs/go-graphsync/pull/332#discussion_r792178486 - mainly because graphsync keeps a tight reign over its allocations so being able to predict helps with that process.
For this reason, it's kind of important this is absolutely correct! Do we have code for generating garbage nodes that I can run through this to get some more certainty about correctness? Something like https://github.com/rvagg/js-ipld-garbage?
(Also feel free to object if you think this is a terrible addition, that's a valid response too.)
=> feat: add dagcbor.EncodedLength(Node) to calculate byte length without encoding

node/bindnode/infer_test.go, node/bindnode/repr.go
Fixes: https://github.com/ipld/go-ipld-prime/issues/367
=> fix(bindnode): tuple struct iterator should handle absent fields properly

node/bindnode/infer_test.go, node/bindnode/node.go
=> node/bindnode: support pointers to datamodel.Node to bind with Any

datamodel/node.go, node/basicnode/bytes.go
We can handle large bytes by allowing Bytes kinded nodes to optionally support
the `ReadAt` method thereby implementing the ReaderAt interface.
This is proposed over a distinct the reader / seeker implementation because the ReaderAt interface is stateless - it does not need the addition of a position cursor to be tracked in the node between calls, while still allowing for partial reads of the node contents.
=> Allow feature detection for `io.ReaderAt` on Bytes nodes

traversal/fns.go, traversal/walk.go, traversal/walk_test.go
This is an alternative way to "resume selector traversals"  - similar to https://github.com/ipld/go-ipld-prime/pull/354 - but tailored to different needs. 
https://github.com/ipld/go-ipld-prime/pull/354 is ideal for someone writing a CAR file who needs to stop on a block boundary and wants to retain information about blocks traversed so they can resume writing at a point.
This is ideal for someone who wants to maintain as little state information as possible and simply execute a selector as if it started at a specific path -- even the visits will not get called before the path. It's deal for a scenario like graphsync resumption -- where transmitting a list of "do not send these blocks" has proved quite problematic in the past (cause of the network overhead on large DAGs)
It's really …
=> Implement option to start traversals at a path

datamodel/node.go
add a comment explaining that ReadSeekers returned by AsLargeBytes must be independent
=> docs(datamodel): add comment to LargeBytesNode

node/bindnode/infer.go, node/bindnode/infer_test.go
=> node/bindnode: enforce pointer requirement for nullable maps

codec/dagcbor/unmarshal.go, codec/dagcbor/unmarshal_test.go, node/bindnode/fuzz_test.go
Just re-using an approach that's used by the dag-json codec rather than trying to hack refmt which won't properly support this kind of inspection since it only considers complete terminal sets rather than caring about where the bytes stop.
This does mean https://github.com/ipld/go-ipld-prime/issues/374 will apply to dag-cbor too, but that's appropriate - we should be erroring here and allowing the user to opt-in (somehow!) to allowing it to go only up to the end of the terminal set and no more.
---
To try out the fuzz thing I grabbed go 1.18 and ran `go test -fuzz=FuzzBindnodeViaDagCBOR` in `node/bindnode` to make it run and the `a000` case is fixed there, but it still fails:
```
fuzz: elapsed: 0s, gathering baseline coverage: 0/25 completed
fuzz: elapsed: 0s, gathering baseline coverage: …
```
=> fix(dagcbor): don't accept trailing bytes

codec/dagcbor/unmarshal.go, node/bindnode/fuzz_test.go, node/bindnode/testdata/fuzz/FuzzBindnodeViaDagCBOR/425499b0c3693d87a0b11db10d21c540283dfb88610d114eb5b23485d5c2f342
=> codec/dagcbor: add DecodeOptions.ExperimentalDeterminism

schema/dmt/compile.go, schema/dsl/parse.go
Adds support for `representation stringjoin` for structs and `representation stringprefix` for unions.
=> dsl support for stringjoin struct repr and stringprefix union repr

.github/workflows/test.yml, schema/gen/go/testLinks_test.go, schema/gen/go/testLists_test.go, schema/gen/go/testMaps_test.go, schema/gen/go/testScalars_test.go, schema/gen/go/testStructReprStringjoin_test.go, schema/gen/go/testStructReprTuple_test.go, schema/gen/go/testStruct_test.go, schema/gen/go/testStructsContainingMaybe_test.go, schema/gen/go/testUnionsKinded_test.go, schema/gen/go/testUnionsStringprefix_test.go, schema/gen/go/testUnions_test.go
There's an underlying bug (or set of them) here that is causing problems on macos. A temporary fix to get macos into CI is to disable the parallelism but we really need to find the real cause and fix that.
It'd be nice to be able to iterate toward being able to enable the unified-ci setup here and this is one of the main blockers I believe (Windows is another story).
Ref: https://github.com/ipld/go-ipld-prime/issues/79
=> Disable gen-go parallelism when testing on macos to enable macos in CI

node/bindnode/example_test.go, node/bindnode/infer.go, node/bindnode/infer_test.go, node/bindnode/node.go
=> node/bindnode: allow nilable types for IPLD optional/nullable

schema/dmt/compile.go, schema/dsl/parse.go, schema/gen/go/generate.go
PR to ipld/ipld coming up after this for fixtures
This lets the schema parser parse things like:
```
type LinkMap {String:&Boom}
type MapMap {String:{String:Boom}}
type ListMap {String:[Boom]}
```
enabled for links, maps, structs, keyed and kinded unions, for inline maps, lists and links (which have their own awkwardness)
=> schema: enable inline types through dsl parser & compiler

.gitattributes, .github/workflows/test.yml, schema/dmt/roundtrip_test.go, schema/dsl/parse_test.go, schema/gen/go/externUtil.go, schema/gen/go/testEngine_disabled_test.go, schema/gen/go/testEngine_plugin_test.go, traversal/selector/spec_test.go
I don't have a good excuse for doing this other than it's _Hack Week_ and this is an itch that wanted scratching
=> test: make tests work on Windows, add Windows to CI

.github/workflows/test.yml, codec/dagcbor/unmarshal.go, codec/dagcbor/unmarshal_test.go, schema/gen/go/testEngine_nocgo_test.go
Another step in the unified-ci process
=> fix: make 32-bit safe and stable & add to CI

node/bindnode/api.go, node/bindnode/custom_test.go, node/bindnode/infer.go, node/bindnode/node.go
Continuing #414, this adds a `AddCustomTypeAnyConverter()` option. It can handle maps, lists and all scalar kinds (including Null, which is a weird one since we're talking about `nullable` fields). A receiving Go type that is registered as a CustomTypeAnyConverter will receive a `datamodel.Node` and is expected to return one when converting to and from that custom Go type.
Still need to consider whether these need doing and how best to do it & test for it:
* `_mapIterator#Next()`
* `_listIterator#Next()`
* `_node#LookupByString()`
* `_node#LookupByIndex()`
and unions.. not fully sure about how unions fit into any of this yet.
The tests in here might be worth a look, there's two variations of an `Any` converter - one expects a Map that's of a very particular form and encodes and decodes it …
=> feat(bindnode): add AddCustomTypeAnyConverter() to handle `Any` fields

node/bindnode/api_test.go, node/bindnode/repr.go
Fixes: https://github.com/ipld/go-ipld-prime/issues/348
=> fix(bindnode): more helpful error message for enum value footgun

node/bindnode/api_test.go
Closes: https://github.com/ipld/go-ipld-prime/issues/339
I can't repro the error in #339, so I'm adding this test and will close the issue. I've also tried it with 0.14.4 which is the version used in the issue and it passes so I'm clearly not hitting it quite right. But without additional information I'm going to have to wait for someone else to stumble across the problem before it can be fixed.
Unless someone else has a good idea for what unaddressable values I can try out, or how I might be able to trigger the problem indicated.
=> chore(bindnode): add test for sub-node unwrapping

codec/dagcbor/marshal.go, codec/dagcbor/marshal_test.go, codec/dagjson/marshal.go, codec/dagjson/marshal_test.go
Otherwise we end up with invalid output like this:
dag-cbor: `0xd82a4100`
```
d8 2a                                           #   tag(42)
41                                            #     bytes(1)
00                                          #       "\x00"
```
dag-json: `{"/":"b"}`
Fixes: https://github.com/ipld/go-ipld-prime/issues/246
---
@aschmahmann @willscott I'd appreciate your 👍 on this as it's a coercion rather than an error or other funky behaviour. But this probably isn't that simple:
* Unlike string, or int, the zero-value of CID doesn't have a round-trippable form that we've come up with for any of our codecs, so we're essentially making one up here, `null`. The alternative may be to define a null CID for both of these codecs - we could just use the values above and make it …
=> fix(codecs): coerce cid.Undef to null in dag{json,cbor} output

datamodel/path.go, traversal/focus.go, traversal/patch/eval.go, traversal/patch/parse.go, traversal/patch/patch.go, traversal/patch/patch.ipldsch, traversal/patch/patch_serial.go, traversal/patch/patch_test.go
(Work in progress.)
The JSON Patch specification is pretty decent; this roughly follows it.
Most of the heavy lifting is done by shelling out to the existing
traversal.FocusedTransform functions.  We're just gluing that to a more
declarative API, which is more ready to be used via a serial API.
The performance of this system in the face of multiple patch operations
on the same target is probably abysmal.  This implementation is an MVP.
It's likely that a smarter implementation could combine more than one
operation application onto the same data build process, and thus
induce a *lot* fewer copies.  This also gets much trickier to implement
(maybe you need some patricia trees for ordering operations?  or more
mutable nodes for the duration of the computation, then ideally a way
to freeze …
=> patch: first draft.

codec/dagjson/nongreedy_test.go, codec/dagjson/unmarshal.go
Resolves https://github.com/ipld/go-ipld-prime/issues/374.
=> add option to not parse beyond end of structure

codec/dagcbor/marshal.go, codec/dagcbor/roundtrip_test.go, codec/dagcbor/unmarshal.go, datamodel/node.go, node/basicnode/int.go
I don't think I'd dare do this without Eric's OK so it's a draft for now. This _should_ allow us to access the full positive uint64 range of integers, although you can only get to it by type checking and accessing some custom methods.
I'm mainly thinking about this for bindnode, when you have a `uint64` you can actually encode and decode the full range rather than overflowing the signed bit when casting to int64 for the highest range of integers. The awkward cast to the `uintNode` shaped type wouldn't be a big deal tucked away in bindnode and it's not really something we have to advertise publicly unless folks complain and want their full range.
This doesn't handle the negative uint64 range, which cbor can do, that would require some plumbing through refmt which currently errors when it …
=> feat: representation of full uint64 range in & out of cbor

HACKME_releases.md
Closes: https://github.com/ipld/go-ipld-prime/issues/387
Ref: https://github.com/ipld/go-ipld-prime/issues/384#issuecomment-1061964620
Putting into practice @ https://github.com/ipld/go-ipld-prime/pull/440 for v0.17.0
=> feat: add release checklist

node/bindnode/api.go, node/bindnode/api_test.go, node/bindnode/custom_test.go, node/bindnode/infer.go, node/bindnode/node.go, node/bindnode/repr.go
This arises out of the attempts to push bindnode down into go-fil-markets for go-data-transfer vouchers. There are some types that are difficult to handle without just replacing them and having a conversion layer.
(Skip to custom_test.go for the code TL;DR)
To give some idea of the challenges, here's the list of types in their hierarchies that become difficult:
- `retrievalmarket.DealResponse`
- `go-state-types/abi/TokenAmount` - `go-state-types/big/Int` - `struct{*big.Int}`
- `retrievalmarket.DealProposal`
- `retrievalmarket.Params`
- `go-state-types/abi/TokenAmount` - `go-state-types/big/Int` - `struct{*big.Int}`
- `retrievalmarket.DealPayment`
- `go-address/Address` - `struct{string}`
- `specs-actors/actors/builtin/paych/SignedVoucher`
- `go-address/Address` - `struct{string}`
- …
=> feat(bindnode): allow custom type conversions with options

node/bindnode/registry/registry.go, node/bindnode/registry/registry_test.go
For centralising bindnode setup - register a type & schema once and not have to
worry about the TypedPrototype or direct bindnode calls after that. It also
caches bindnode Options that may go along with the type.
This could have been a global registry, but there exists a possibility of the
same type wanting to be used by different users in the same application
instance but with different schemas and/or Options. So instead, the question of
it being a global is left to the user.
---
This is the core of work I've been distilling in go-fil-markets and go-data-transfer and is an evolution of something that's currently in go-graphsync. There's really not a lot to this, it just simplifies the setup management, and when we have `Options` involved too it makes it a _lot_ easier than needing them …
=> feat(bindnode): add a BindnodeRegistry utility

codec/dagjson/marshal.go, codec/dagjson/marshal_test.go, codec/json/marshal_test.go
The plain JSON codec shouldn't be able to encode bytes or links and should consistently error. The DAG-JSON codec should be able to, of course.
I'll do a simple 0.18.1 after this, but in a separate PR that updates the changelog and does the proper release process.
=> fix: correct json codec links & bytes handling

datamodel/link.go, linking/functions.go, linking/functions_test.go
On load, the default IPLD Link System checks the hash of loaded data against the given hash to assure that they match. The actual hash is calculated using the given link's `LinkPrototype.BuildLink`, and then is directly compared with the given link via `==`.
Because the comparison is done by value, if the given link is a pointer the comparison fails which will result in false-positive hash mismatch error.
To address this issue, instead of directly comparing objects using `==` check that their `Binary` value, i.e. their densest possible encoding, is equal. Add tests that assert the issue is fixed and works with existing link representations.
=> Fix hash mismatch error on matching link pointer

node/bindnode/fuzz_test.go, schema/dmt/operations.go, schema/dmt/roundtrip_test.go, schema/dmt/schema.go, schema/dsl/parse_test.go
This is a small diff which introduces a bit more ability to introspect and operate on `schema/dmt` data.
Making the type system accessible makes it easier to manipulate the schema DMT _as IPLD_, which is a very neat thing to be able to do.  (Some of this is already possible because `schemadmt.Type.Schema` is exported specifically; but I see no reason not to export the entire typesystem.)
Then, a function is introduced which can conjoin two parsed schema DMT documents.  (This stops just shy of introducing an "include" syntax to IPLD Schemas, but one can see how it could easily be involved in producing such a feature.)
=> Additional access to schema/dmt package; schema concatenation feature

codec/dagcbor/nongreedy_test.go, codec/dagcbor/unmarshal.go
Petar added this in #435 for dag-json but I find myself now wanting the same for dag-cbor! The test and functionality mirror the dag-json implementation; it's all refmt anyway so basically the same process.
=> feat(dagcbor): mode to allow parsing undelimited streamed objects

traversal/walk.go, traversal/walk_test.go
The test for this was too easy and doesn't pass if you give it other things to match _prior_ to the `StartAtPath`. New test added for the non-matching case, which is where this functionality is actually used (graphsync), and that works properly already.
=> fix: make StartAtPath work properly for matching walks

traversal/walk.go, traversal/walk_test.go
It looks like the current implementation never calls Selector.Decide(), meaning it always attempts to transform the root node, even if it shouldn't be matched.
=> Make traversal.WalkTransforming() work

schema/gen/go/testEngine_disabled_test.go
We get this error showing up in CI fairly regularly. So I'm starting by taking the brute-force approach, just delete anything that's .exe before a `go build` in that directory.
=> fix(windows,test): avoid "already exists" error on codegen tests for windows

node/bindnode/node.go, node/bindnode/repr.go, node/tests/schema.go, node/tests/schemaStructReprListpairs.go, schema/dmt/compile.go, schema/dsl/parse.go, schema/tmpBuilders.go, schema/type.go, schema/typeMethods.go
I want order-preserving structs without a pre-defined strict order (tuple), so this implements listpairs which is in the schema spec but has sparse support through go-ipld-prime.
```ipldsch
type Blop struct {
foo optional Int
bar optional String
baz optional String
} representation listpairs
```
```go
type Blop struct {
Foo *int
Bar  *string
Baz *string
}
```
```json
[ "foo", 100, "baz", "bing" ]
```
_(edit: actually should be this:)_
```json
[ [ "foo", 100 ], [ "baz", "bing" ] ]
```
But also this should decode to the same struct (see `out-of-order` test):
```json
[ "baz", "bing", "foo", 100 ]
```
_(edit: actually should be this:)_
```json
[ [ "baz", "bing" ], [ "foo", 100 ] ]
```
=> feat(bindnode): support listpairs struct representation

node/basicnode/int.go
`basicnode.NewInt` should return a pointer to `plainInt`, similarly to the other types (string, float, bytes, etc). When writing tests for [this PR](https://github.com/ipfs/boxo/pull/333) and mocking interfaces, I was getting a pretty interesting error: the `Decoded` version of an `int` was returning a `*plainInt`, while the `basicnode.NewInt` was returning `plainInt`, causing the mock to fail.
All the other node types work well. There is an inconsistency between how ints are created and assigned. This does not happen with other types. I assume this was something overlooked. It would be nice if this could get released.
cc @rvagg
=> fix: basicnode.NewInt returns pointer (like others)

node/tests/byteSpecs.go, testutil/multibytenode.go, testutil/multibytenode_test.go, traversal/selector/matcher.go, traversal/selector/matcher_test.go, traversal/selector/matcher_util.go
~~Draft for now; this is fine but I need to make sure there's nothing else needed here for this piece of byte range queries (there's also more pieces).~~
* Don't error slice matcher when not string or bytes, silently non-match
* Cache offset in `readerat` so we don't over-all on the underlying read seeker
* Add lots of tests, including various edges
* Fix 32-bit breakage exposed by tests
=> fix(selectors): slice matcher fixes & tests

testutil/simplebytes.go, traversal/selector/matcher.go, traversal/selector/matcher_test.go, traversal/selector/spec_test.go
Ref: https://github.com/ipld/ipld/pull/289
Builds on the basic fixes and tests in: https://github.com/ipld/go-ipld-prime/pull/529
Note particularly the nuances in the test cases for negative values as they relate to what I outlined in https://github.com/ipld/ipld/pull/289.
One implication of the way this is implemented is that we can't do the "your range didn't match, so we'll give you the full file". We end up with "didn't match, you get nothing (just the root)". Which seems like logical behaviour to me, but @willscott you did bring up the http spec saying that you could return the whole lot if your range is OOB or invalid in some way.
=> feat(selectors): negative values for slice matcher's From and To

datamodel/path.go, datamodel/pathSegment.go, datamodel/path_test.go, traversal/walk.go
This might require a little bit more thought than I've put into it so far, but this mainly comes from some code that has `var nextSeg datamodel.PathSegment`, then using that naively when it's not initialised, for `String()` in particular. I normally initialise it in a loop using a `path.Shift()` operation but with `Len()==0` I have the zero value. My assumption was that the zero value would just be empty and I could be fine with that. But even if I did a `path.Shift()` on an empty path, I'd get the same thing. Which is, the zero value of a `PathSegment` is a `0` index. This is probably reasonable in some situations but doing a `nextSeg.String()` and seeing `"0"` was certainly not expected.
There is some awkwardness, but it's not new, here's some variations of awkward things you can do, …
=> feat: add EmptyPathSegment, distinct from PathSegment{}

schema/dmt/compile.go, schema/tmpBuilders.go
fix #568
add more minimal form of schema compilation and useful functions for merging one type system into another. this would enable the various types of schema type system building I discussed in #568.
Note that most of these functions have been written without access to private data members, in part cause until this is merged I'm just going to build on top. The absolute minimal version of this PR would simply make `spawnType` at https://github.com/ipld/go-ipld-prime/blob/master/schema/dmt/compile.go#L135 a public function `SpawnType` (just to avoid a large copy paste). Pretty much everything else could be built outside the library if you want to target the minimal form.
However, one can see that some of the functions would probably be better with private members. Clone for example is …
=> feat(schema): expose useful functions for building schemas

node/basicnode/list.go
I'm not too sure what error should be returned, but it's certainly better than a panic().
=> basicnode: don't panic on negative index

codecHelpers.go
a user of the codec helpers might want to be able to use custom bindnode options to assist in Mashalling/Unmarshalling their types
Add opts ...bindnode.Options as parameter to various helpers and pass it through to the underlying bindnode functions.
Pretty sure it's fine but passing bindnode options to both prototype call and wrap call in UnmarshalStreaming could have unintended effects? Not sure which is should properly go to though.
=> Thread bindnode options through convenience calls

node/bindnode/api.go, node/bindnode/custom_test.go, node/bindnode/infer.go, node/bindnode/node.go, node/bindnode/repr.go
Currently, the bindnode API enables custom conversions, keyed on go types.
This PR enables a new way to key custom conversions: the type name in a schema.
Why is this useful?
- First it enables using standard go types for custom conversions, rather than needing to create a named go type every time you want a converter
- More interestingly, it enables using interface types within structs, lists, and maps -- since the conversion is keyed on the schema type name, the go type isn't needed to setup a custom conversion, and then the convert can create types that satisfy the interface -- this is super useful for more flexible go structs.
- For compatibility, this keeps all typed custom converter APIs working, with schema named converters taking preference. This does mean that the `config` type …
=> Named type converters
