ipld/go-ipld-prime

linking/cid/cidLink.go
See slack message re: mem allocations + io.ReadAll
=> fix(cidlink): check for byte buffer

schema/gen/go/generate.go
=> add import to ipld in ipldsch_types.go

fluent/qp/qp.go
=> fluent/qp: don't panic on string panics

node/bindnode/example_test.go, node/bindnode/node.go, node/bindnode/repr.go
=> node/bindnode: start of a reflect-based Node implementation

node.go
Per https://github.com/ipld/go-ipld-prime/issues/175 and some discussions today.
(Also touched up the docs for Next vs Done a bit while I was in the area;
they're not significantly changed, but there were some dangling antecedents
that didn't read very well, and now it's a bit better.)
=> Add more explicit discussion of indicies to ListIterator.

node/bindnode/node.go, node/bindnode/schema_test.go, node/tests/schema.go, node/tests/schemaMaps.go, node/tests/testcase.go
=> node/bindnode: start running all schema tests

node/bindnode/node.go, node/bindnode/repr.go, node/tests/schemaScalars.go
=> node/tests: cover more error cases for scalar kinds

node/basic/any_test.go, node/basic/bench_test.go, node/basic/list_test.go, node/basic/map_test.go, node/basic/string_test.go, node/bindnode/node.go, node/bindnode/repr.go, node/tests/schemaLists.go, node/tests/schemaScalars.go, node/tests/schemaStruct.go
=> node/tests: cover yet more interface methods

node/bindnode/example_test.go, node/bindnode/infer.go, node/bindnode/node.go
=> node/bindnode: first pass at inferring IPLD schemas

codec/dagcbor/unmarshal.go, codec/dagjson/unmarshal.go, codec/decode_test.go, go.mod, go.sum, multicodec/registry.go
=> codec: make cbor and json codecs use ErrUnexpectedEOF

node/bindnode/generate.go, schema/dmt/gen_test.go, schema/dmt/schema.go, schema/dmt/types.go, schema/tmpBuilders.go, schema/typesystem.go
=> schema: keep TypeSystem names ordered

fluent/qp/qp.go, node/bindnode/infer.go, node/bindnode/node.go, node/bindnode/repr.go, printer/printer.go, schema/dmt/build.go, schema/gen/go/generate.go, schema/tmpBuilders.go, schema/type.go
=> schema: turn TypeName into an alias

node/bindnode/api.go, node/bindnode/infer.go, node/bindnode/infer_test.go, node/bindnode/node.go, node/bindnode/repr.go, node/bindnode/schema_test.go
(see commit messages - please do not squash)
=> node/bindnode: more support for kinded unions, polish some panics

node/bindnode/infer.go, node/bindnode/infer_test.go
=> node/bindnode: support links in schema-type verification

.github/workflows/test.yml, printer/printer_test.go
=> bump CI to Go 1.16 and 1.17

node/bindnode/generate.go, node/bindnode/infer_test.go
=> node/bindnode: support links in ProduceGoTypes

go.mod, printer/printer_test.go, schema/gen/go/genpartsMinima.go, schema/gen/go/mixins/templateUtil.go, schema/gen/go/templateUtil.go, testutil/indent.go, testutil/indent_test.go
Fork `wish.Dedent` code into `testutil` package along with its test and
replace references to `go-wish` with forked function.
=> Remove dependency to `go-wish`

schema/dmt/compile.go, schema/dsl/parse.go
=> schema: add support for struct tuple reprs

node/bindnode/infer.go, node/bindnode/infer_test.go
=> node/bindnode: allow binding cidlink.Link to links

schema/dmt/compile.go, schema/dsl/parse.go
=> schema/...: add support for enum int representations

node/bindnode/generate.go, node/bindnode/infer.go, node/bindnode/infer_test.go, node/bindnode/repr.go
=> node/bindnode: add support for enums

node/bindnode/generate.go, node/bindnode/infer.go, node/bindnode/infer_test.go, node/bindnode/node.go, node/bindnode/repr.go, schema/dmt/compile.go, schema/dsl/parse.go, schema/kind.go, schema/tmpBuilders.go, schema/type.go, schema/typeMethods.go
=> schema,node/bindnode: add support for Any

node/bindnode/infer.go, node/bindnode/infer_test.go, node/bindnode/repr.go
=> node/bindnode: allow mapping int-repr enums with Go integers

codec/dagcbor/marshal.go, codec/dagjson/marshal.go, node/bindnode/repr.go
Further to #332 I figured it'd be good to insert this sanity check so we can't produce this kind of malformed data at the codec level. I was wondering how I might add a test for this since it requires a dodgy type, but it turns out bindnode fails with AbsentOptionals when this is added, so that at least tells me this is correct.
Do you think this warrants adding a test? I think it would mean writing a full, dodgy, map type that reports the wrong `Length()`.
=> fix(codecs): error when encoding maps whose lengths don't match entry count

node/bindnode/infer.go, node/bindnode/infer_test.go, node/bindnode/node.go, node/bindnode/repr.go
=> node/bindnode: improve support for pointer types

node/bindnode/example_test.go
=> node/bindnode: start using ipld.LoadSchema APIs

datamodel/errors.go, datamodel/kind.go, datamodel/kind_test.go, go.mod, go.sum, node/bindnode/infer_test.go, node/bindnode/node.go, node/bindnode/repr.go
(see commit messages - please do not squash)
Updates #342.
=> a couple of panic fixes

node/bindnode/infer_test.go, node/bindnode/node.go, node/bindnode/repr.go
=> node/bindnode: introduce an assembler that always errors

node/bindnode/infer_test.go, node/bindnode/node.go, node/bindnode/repr.go
=> node/bindnode: polish some more AsT panics

node/bindnode/infer.go, node/bindnode/infer_test.go, node/bindnode/node.go, node/bindnode/repr.go
=> node/bindnode: add support for unsigned integers

examples_test.go
=> add top-level "go value with schema" example

node/bindnode/fuzz_test.go, node/bindnode/infer.go, node/bindnode/repr.go, node/bindnode/testdata/fuzz/FuzzBindnodeViaDagCBOR/2c17d42168478a0837ebba66f6aa98bdf4bb81b5196062d0e6b23c8b0325be6a, node/bindnode/testdata/fuzz/FuzzBindnodeViaDagCBOR/821c248529299bb6b68e443e4b00cc11c6605f766f25e619d85e6d6b40a33dac
=> node/bindnode: start fuzzing with schema/dmt and codec/dagcbor

node/bindnode/api.go, node/bindnode/fuzz_test.go, node/bindnode/infer.go, node/bindnode/node.go, node/bindnode/testdata/fuzz/FuzzBindnodeViaDagCBOR/164dd28629e6a5637f02c6eaad32eee5bf8ea41ce6d1dae95334a7db7dd6188f, node/bindnode/testdata/fuzz/FuzzBindnodeViaDagCBOR/199afa754020c4587bc87633033b4e56ecdb5ecc2bb0dbac46b799d6c18c5201, node/bindnode/testdata/fuzz/FuzzBindnodeViaDagCBOR/636f8e5cdaf52572b826e615a9bdf90f15f8acf2880b467b3949f5356c2ddded, node/bindnode/testdata/fuzz/FuzzBindnodeViaDagCBOR/669d57fbbe55b8ceb7e78e3ccd3b90e76c4b740d25284a66eac8aac0dbb2475d, node/bindnode/testdata/fuzz/FuzzBindnodeViaDagCBOR/7f9a6898dead41ba2f5fd4f07f2ddb44d54e7648d66e54982d09996bc720cf56, node/bindnode/testdata/fuzz/FuzzBindnodeViaDagCBOR/bf7c410983f3e696a03e743df1bc6f606137871f7fb557af74836b7aa04e56ad, node/bindnode/testdata/fuzz/FuzzBindnodeViaDagCBOR/dc95e9aad454ed9109e93b824f92d4bb00c9c778af29e6fcb38a6083c78d7dbb, node/bindnode/testdata/fuzz/FuzzBindnodeViaDagCBOR/f63d4652cdac3208fc0a0d0b755615320443b60ef80c0ecdef99c9d895ae2124, node/bindnode/testdata/fuzz/FuzzBindnodeViaDagCBOR/fe73a19655fff8b93193c3e90f9cd7b24b10ae0467175cf2264ff3ec135215a6, schema/dmt/compile.go
(see commit messages - please do not squash)
=> many more fuzz fixes

node/bindnode/fuzz_test.go
=> node/bindnode: minor fuzz improvements

README.md
These probably aren't perfect, but they're better than nothing :)
Capturing these pointers into the readme seems like a good idea after I just found myself having to go find them and point them out in response to some questions in matrix the other day.
=> readme: getting started pointers.

node/bindnode/node.go, node/bindnode/repr.go
=> node/bindnode: add some more docs

.github/dependabot.yml
=> chore(deps): expand dependabot to sub-modules

node/gendemo/gen.go, node/gendemo/ipldsch_satisfaction.go, node/gendemo/ipldsch_types.go
Kinded unions are hard .. I wanted to see what gen was doing with a kinded union so I could sanity check that I'm dealing with it properly in some JavaScript. I figured I'd commit it here since I went to the effort of making this. It matches a test fixture I have in JS that I think came out of some schema fixtures that landed in ipld/ipld, at some point I'll try and make those meet and be used here.
=> feat: add kinded union to gendemo

schema/dmt/compile.go, schema/dsl/parse.go, schema/tmpBuilders.go
Closes: https://github.com/ipld/ipld/pull/286
Depends on: https://github.com/ipld/ipld/pull/286
... because why not, gotta get this parser finished out, can't let the JS one have all the glory
=> feat: add inline union representation to schema parser

HACKME_builderBehaviors.md, README.md, multicodec/defaultRegistry.go, storage/api.go, storage/doc.go, storage/tests/benchmarks.go, traversal/patch/patch.ipldsch
=> Corrected texts

HACKME.md, codec/api.go, codec/dagcbor/unmarshal.go, codecHelpers.go, linking/cid/HACKME.md, linking/cid/cidLink.go, schema/dmt/schema.go, schema/gen/go/HACKME.md, schema/gen/go/HACKME_maybe.md, schema/gen/go/HACKME_memorylayout.md, schema/gen/go/HACKME_scalars.md, schema/gen/go/HACKME_testing.md, schema/gen/go/adjunctCfg.go, schema/gen/go/genList.go, schema/gen/go/genStructReprStringjoin.go, schema/gen/go/genUnion.go, schema/gen/go/genUnionReprKinded.go, schema/gen/go/genUnionReprStringprefix.go, testutil/garbage/garbage.go
=> Multiple text corrections

schema/gen/go/HACKME_abbrevs.md, schema/gen/go/HACKME_tradeoffs.md, schema/gen/go/HACKME_wip.md, schema/gen/go/genMap.go, schema/gen/go/genStructReprTuple.go, schema/gen/go/genUnion.go, schema/gen/go/generators.go, schema/gen/go/mixins/kindTraits.go
Text corrections including multiple panic messages in go file.
=> Text corrections

adl/rot13adl/rot13node.go, adl/rot13adl/rot13node_test.go, datamodel/node.go, datamodel/path.go, datamodel/pathSegment.go, examples_test.go, printer/doc.go, printer/printer.go
=> Corrections on go files
